security:
  providers:
    fetcher:
      id: App\Application\Security\UserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      user_checker: App\Application\Security\UserChecker
      guard:
        authenticators: [
          App\Application\Security\LoginFormAuthenticator,
          App\Application\Security\FacebookAuthenticator
        ]
      entry_point: App\Application\Security\LoginFormAuthenticator
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800
        path: /
  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER]
  access_control:
    #- { path: ^/confirm, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/sign-in, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/sign-up, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/oauth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/, roles: ROLE_USER }

