parameters:
    locale: 'ru'
    fromEmail: '%env(FROM_EMAIL)%'
    defaultDistributor: '%env(DEFAULT_DISTRIBUTOR)%'
    maxGamesPerPage: '%env(MAX_GAMES_PER_PAGE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    pagerfanta.route_generator_factory:
        class: App\Infrastructure\Paginator\RouteGeneratorFactory

    App\:
        resource: '../src'
        exclude: '../src/{**/Migration,Entity,Kernel.php}'

    App\Infrastructure\Doctrine\EventListener\FixPostgresDefaultSchemaListener:
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema }
    App\Infrastructure\Http\Controller\IndexController:
        arguments:
            $defaultDistributor: '%defaultDistributor%'
            $maxGamesPerPage: '%maxGamesPerPage%'

    App\Application\Repository\IUserRepository:
        class: App\Infrastructure\Repository\UserRepository
    App\Application\Repository\IGameRepository:
        class: App\Infrastructure\Repository\GameRepository
    App\Application\Repository\IGenreRepository:
        class: App\Infrastructure\Repository\GenreRepository
    App\Application\Repository\IDistributorRepository:
        class: App\Infrastructure\Repository\DistributorRepository
    App\Application\Service\IFlusher:
        class: App\Infrastructure\Service\Flusher
    App\Infrastructure\Service\IConfirmTokenSender: '@App\Infrastructure\Service\ConfirmTokenSender'
    Predis\ClientInterface:
        class: Predis\Client
        arguments: ['%env(REDIS_URL)%']
    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments: ['@Predis\ClientInterface']
    App\Infrastructure\Service\ConfirmTokenSender:
        $from: '%fromEmail%'
    App\Infrastructure\Service\ResetTokenSender:
        $from: '%fromEmail%'
    App\Infrastructure\Service\ResetTokenizer:
        factory: App\Infrastructure\DI\Factory\ResetTokenizerFactory::create
        arguments:
            $interval: 'PT1H'
